apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:alpine # Replace with your application image
        volumeMounts:
        - name: config-volume
          mountPath: "/var/data"
      volumes:
      - name: config-volume
        configMap:
          name: app-config
