apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: myapp
spec:
  capacity:
    storage: 2Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: aws-ebs
  awsElasticBlockStore:
    volumeID: vol-0113e1bc53dd39909
    fsType: ext4